language: ruby

rvm:
  - 1.9.3

branches:
  only:
    - master
    - CRUD

services:
  - redis-server

notifications:
  email: false

script:
  - bundle exec rake test

before_script:
  - psql -c 'create database ontohub_test;' -U postgres
  - sudo apt-add-repository -y ppa:hets/hets
  - sudo apt-add-repository -y "deb http://archive.canonical.com/ubuntu precise partner"
  - sudo apt-get update
  - sudo apt-get install hets-core subversion
  - sudo hets -update
  - bundle exec rake db:migrate || true
