language: ruby

rvm:
  - 1.9.3
  - 2.0.0-preview2
  - rbx-19mode

branches:
  only:
    - master

services:
  - redis-server

notifications:
  email: false

script:
  - bundle exec rake test

before_script:
  - psql -c 'create database ontohub_test;' -U postgres
  - apt-add-repository ppa:hets/hets
  - apt-add-repository "deb http://archive.canonical.com/ubuntu precise partner"
  - apt-get update
  - apt-get -y install hets-core subversion
  - cd /lib/x86_64-linux-gnu/
  - ln -s libpng12.so.0 libpng14.so.14
  - hets -update
