language: ruby

rvm:
  - 1.9.3
  - 2.0.0

branches:
  only:
    - master
    - CRUD
    - display_of_symbols

services:
  - redis-server

notifications:
  email: false

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - bundle exec rake test

before_script:
  - psql -c 'create database ontohub_test;' -U postgres
  - sudo apt-add-repository -y ppa:hets/hets
  - sudo apt-add-repository -y "deb http://archive.canonical.com/ubuntu precise partner"
  - sudo apt-add-repository -y "deb http://archive.ubuntu.com/ubuntu precise-updates universe"
  - sudo apt-get update
  - sudo apt-get install hets-core subversion
  - sudo hets -update
  - bundle exec rake db:migrate || true
