hets_path:
  - /usr/lib/hets/hets
  - ~/uni/awe/Hets/hets
hets_lib:
  - /usr/lib/hets/hets-lib
  - ~/uni/awe/Hets-lib
hets_owl_tools:
  - /usr/lib/hets/hets-owl-tools
  - ~/uni/awe/Hets/OWL2
allowed_extensions:
  - owl
  - clf
  - clif
  - xml
