# Hets environment. The first matching item in the lists is used.
hets_path:
  - /usr/lib/hets/hets
  - ~/uni/awe/Hets/hets
  - /opt/local/bin/hets
hets_lib:
  - /usr/lib/hets/hets-lib
  - ~/uni/awe/Hets-lib
hets_owl_tools:
  - /usr/lib/hets/hets-owl-tools
  - ~/uni/awe/Hets/OWL2
